version: '2.1'

services:

  base:
    build:
      context: .
    volumes:
      - .:/app

  web:
    extends:
      file: docker-compose.yml
      service: base
    ports:
      - "9292:9292"
    command: bash -c "bundle exec rackup -p 9292 -o '0.0.0.0'"
